# Generated by Django 4.2.30 on 2026-08-06 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('nama', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150, null=True)),
                ('role', models.CharField(default='user', max_length=20)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('jabatan', models.CharField(max_length=100, null=True)),
                ('avatar', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Absen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tanggal', models.DateField()),
                ('project_name', models.CharField(max_length=200)),
                ('segmen', models.CharField(max_length=200, null=True)),
                ('waktu_lapor', models.CharField(max_length=20, null=True)),
                ('deskripsi', models.TextField(null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'absen',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=150, null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('address', models.TextField(null=True)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_type', models.CharField(default='po', max_length=20)),
                ('project_name', models.CharField(max_length=200)),
                ('po_number', models.CharField(max_length=100, null=True)),
                ('po_date', models.DateField(null=True)),
                ('description', models.TextField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('status', models.CharField(default='active', max_length=20)),
                ('completed_date', models.DateField(null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.customer')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kunci', models.CharField(max_length=100, unique=True)),
                ('nilai', models.TextField(null=True)),
                ('deskripsi', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'settings',
            },
        ),
        migrations.CreateModel(
            name='SupervisiLaporan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jenis', models.CharField(default='laporan', max_length=20)),
                ('tanggal', models.DateField()),
                ('project_name', models.CharField(max_length=200)),
                ('lokasi', models.CharField(max_length=200, null=True)),
                ('waktu_lapor', models.CharField(max_length=20, null=True)),
                ('judul', models.CharField(max_length=255, null=True)),
                ('catatan', models.TextField(null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.project')),
            ],
            options={
                'db_table': 'supervisi_laporan',
            },
        ),
        migrations.CreateModel(
            name='SupervisiLaporanItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segmen', models.CharField(max_length=200, null=True)),
                ('kategori', models.CharField(max_length=100)),
                ('nama_item', models.CharField(max_length=255)),
                ('nilai', models.DecimalField(decimal_places=3, max_digits=15, null=True)),
                ('satuan', models.CharField(max_length=50, null=True)),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='portal.supervisilaporan')),
            ],
            options={
                'db_table': 'supervisi_laporan_item',
            },
        ),
        migrations.CreateModel(
            name='SupervisiLaporanFoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama_file', models.CharField(max_length=255)),
                ('caption', models.CharField(max_length=255, null=True)),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto', to='portal.supervisilaporan')),
            ],
            options={
                'db_table': 'supervisi_laporan_foto',
            },
        ),
        migrations.CreateModel(
            name='ProjectTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField()),
                ('task_name', models.CharField(max_length=200)),
                ('tanggal', models.DateField()),
                ('status', models.CharField(default='planned', max_length=30)),
                ('notes', models.TextField(null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='portal.project')),
            ],
            options={
                'db_table': 'project_timeline',
            },
        ),
        migrations.CreateModel(
            name='ProjectRAB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kategori', models.CharField(max_length=30)),
                ('deskripsi', models.TextField(null=True)),
                ('satuan', models.CharField(max_length=50, null=True)),
                ('volume', models.DecimalField(decimal_places=3, max_digits=15, null=True)),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rab', to='portal.project')),
            ],
            options={
                'db_table': 'project_rab',
            },
        ),
        migrations.CreateModel(
            name='ProjectOverheadOpname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mandor_name', models.CharField(max_length=200)),
                ('jumlah_pekerja', models.IntegerField(null=True)),
                ('span', models.CharField(max_length=100, null=True)),
                ('item_pekerjaan', models.TextField()),
                ('volume_progress', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('harga_satuan', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('nilai_opname', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('keterangan', models.TextField(null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.project')),
            ],
            options={
                'db_table': 'project_overhead_opname',
            },
        ),
        migrations.CreateModel(
            name='ProjectOverheadKasbonMandor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mandor_name', models.CharField(max_length=200)),
                ('unit_name', models.CharField(max_length=200, null=True)),
                ('plafon', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('kasbon_belum_dibayar', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('pembayaran_terakhir', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('status', models.CharField(default='saldo', max_length=20)),
                ('keterangan', models.TextField(null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.project')),
            ],
            options={
                'db_table': 'project_overhead_kasbon_mandor',
            },
        ),
        migrations.CreateModel(
            name='ProjectJasaSlip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_name', models.CharField(max_length=200)),
                ('period_month', models.CharField(max_length=20)),
                ('posisi', models.CharField(max_length=120, null=True)),
                ('hari_kerja', models.IntegerField(null=True)),
                ('jumlah_gaji', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('tanggal_bayar', models.DateField(null=True)),
                ('keterangan', models.TextField(null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.project')),
            ],
            options={
                'db_table': 'project_jasa_slip',
            },
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_assignments',
            },
        ),
        migrations.CreateModel(
            name='PettyCashBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.project')),
                ('updated_by', models.ForeignKey(db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'petty_cash_budget',
            },
        ),
        migrations.CreateModel(
            name='PettyCash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tanggal', models.DateField()),
                ('kategori', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(null=True)),
                ('jumlah', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('keterangan', models.TextField(null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.project')),
            ],
            options={
                'db_table': 'petty_cash',
            },
        ),
        migrations.CreateModel(
            name='OverheadKantor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tanggal', models.DateField()),
                ('kategori', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(null=True)),
                ('jumlah', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('keterangan', models.TextField(null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'overhead_kantor',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('source', models.CharField(default='gudang', max_length=20)),
                ('used', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.project')),
            ],
            options={
                'db_table': 'materials',
            },
        ),
        migrations.CreateModel(
            name='LogAktivitas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('aksi', models.CharField(max_length=100)),
                ('modul', models.CharField(max_length=100, null=True)),
                ('deskripsi', models.TextField(null=True)),
                ('ip_address', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'log_aktivitas',
            },
        ),
        migrations.CreateModel(
            name='Kasbon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tanggal_pengajuan', models.DateField()),
                ('jumlah', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('keperluan', models.TextField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('tanggal_verifikasi', models.DateTimeField(null=True)),
                ('rejection_reason', models.TextField(null=True)),
                ('keterangan', models.TextField(null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kasbon_requests', to=settings.AUTH_USER_MODEL)),
                ('verifier', models.ForeignKey(db_column='verified_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kasbon',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('po_number', models.CharField(max_length=100)),
                ('po_date', models.DateField(null=True)),
                ('description', models.TextField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('is_additional', models.BooleanField(default=False)),
                ('paid_date', models.DateField(null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.project')),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='AbsenFoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama_file', models.CharField(max_length=255)),
                ('caption', models.CharField(max_length=255, null=True)),
                ('absen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto', to='portal.absen')),
            ],
            options={
                'db_table': 'absen_foto',
            },
        ),
        migrations.CreateModel(
            name='AbsenDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kategori', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('nilai', models.CharField(max_length=100, null=True)),
                ('satuan', models.CharField(max_length=50, null=True)),
                ('absen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='portal.absen')),
            ],
            options={
                'db_table': 'absen_detail',
            },
        ),
        migrations.AddField(
            model_name='absen',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.project'),
        ),
    ]
