# Generated by Django 4.2.30 on 2026-08-06 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=30)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='DRAFT', max_length=20)),
            ],
            options={
                'db_table': 'project_budget_lines',
            },
        ),
        migrations.CreateModel(
            name='ErpInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=80, unique=True)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(default='DRAFT', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'erp_invoices',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=80, unique=True)),
                ('date', models.DateField()),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(default='DRAFT', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='portal.project')),
            ],
            options={
                'db_table': 'customer_purchase_orders',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=30)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='portal.purchaseorder')),
            ],
            options={
                'db_table': 'purchase_order_items',
            },
        ),
        migrations.CreateModel(
            name='ProjectSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='segments', to='portal.project')),
            ],
            options={
                'db_table': 'project_segments',
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='portal.project')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.projectsegment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erp_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_members',
            },
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=80, unique=True)),
                ('period', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('status', models.CharField(default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.purchaseorderitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.project')),
            ],
            options={
                'db_table': 'progress_reports',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='portal.erpinvoice')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='FundRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=80, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('purpose', models.TextField()),
                ('status', models.CharField(default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('budget_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.budgetline')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fund_requests', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.project')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.projectsegment')),
            ],
            options={
                'db_table': 'fund_requests',
            },
        ),
        migrations.CreateModel(
            name='ExpenseReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=80, unique=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('description', models.TextField()),
                ('receipt', models.FileField(blank=True, upload_to='erp/receipts/')),
                ('status', models.CharField(default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fund_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_reports', to='portal.fundrequest')),
            ],
            options={
                'db_table': 'expense_reports',
            },
        ),
        migrations.AddField(
            model_name='erpinvoice',
            name='progress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.progressreport'),
        ),
        migrations.AddField(
            model_name='erpinvoice',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.project'),
        ),
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fund_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursements', to='portal.fundrequest')),
            ],
            options={
                'db_table': 'disbursements',
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=80, unique=True)),
                ('report_date', models.DateField()),
                ('activity', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('attachment', models.FileField(blank=True, upload_to='erp/daily/')),
                ('status', models.CharField(default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_reports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.project')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.projectsegment')),
            ],
            options={
                'db_table': 'daily_reports',
            },
        ),
        migrations.AddField(
            model_name='budgetline',
            name='po_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.purchaseorderitem'),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='portal.project'),
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(max_length=40)),
                ('object_id', models.PositiveBigIntegerField()),
                ('decision', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'approvals',
            },
        ),
        migrations.AddConstraint(
            model_name='projectsegment',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='uniq_project_segment_code'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.UniqueConstraint(fields=('project', 'code', 'version'), name='uniq_budget_version'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['module', 'object_id'], name='approvals_module_29f463_idx'),
        ),
    ]
