from django.urls import path

from . import views

app_name = "erp"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("projects/", views.project_list, name="project-list"),
    path("projects/create/", views.project_form, name="project-create"),
    path("projects/<int:project_id>/edit/", views.project_form, name="project-edit"),
    path("projects/<int:project_id>/deactivate/", views.project_deactivate, name="project-deactivate"),
    path("projects/<int:project_id>/delete/", views.project_delete, name="project-delete"),
    path("projects/<int:project_id>/segments/create/", views.segment_form, name="segment-create"),
    path("projects/<int:project_id>/segments/<int:pk>/edit/", views.segment_form, name="segment-edit"),
    path("projects/<int:project_id>/segments/<int:pk>/delete/", views.segment_delete, name="segment-delete"),
    path("projects/<int:project_id>/members/create/", views.member_form, name="member-create"),
    path("projects/<int:project_id>/members/<int:pk>/edit/", views.member_form, name="member-edit"),
    path("projects/<int:project_id>/members/<int:pk>/delete/", views.member_delete, name="member-delete"),
    path("projects/<int:project_id>/", views.project_dashboard, name="project-dashboard"),
    path("projects/<int:project_id>/services/", lambda request, project_id: views.project_budget(request, project_id, "services"), name="project-services"),
    path("projects/<int:project_id>/materials/", lambda request, project_id: views.project_budget(request, project_id, "materials"), name="project-materials"),
    path("projects/<int:project_id>/overhead/progress/", lambda request, project_id: views.project_budget(request, project_id, "overhead"), name="project-overhead"),
    path("projects/<int:project_id>/overhead/foreman-advances/", views.project_foreman_advances, name="project-foreman-advances"),
    path("projects/<int:project_id>/petty-cash/", lambda request, project_id: views.project_budget(request, project_id, "petty-cash"), name="project-petty-cash"),
    path("projects/<int:project_id>/budget/<str:category>/create/", views.project_budget_form, name="project-budget-create"),
    path("projects/<int:project_id>/budget/<str:category>/<int:pk>/edit/", views.project_budget_form, name="project-budget-edit"),
    path("projects/<int:project_id>/budget/<str:category>/<int:pk>/delete/", views.project_budget_delete, name="project-budget-delete"),
    path("purchase-orders/", views.po_list, name="po-list"),
    path("purchase-orders/create/", views.po_form, name="po-create"),
    path("purchase-orders/<int:pk>/edit/", views.po_form, name="po-edit"),
    path("fund-requests/", views.fund_list, name="fund-list"),
    path("fund-requests/create/", views.fund_form, name="fund-create"),
    path("fund-requests/<int:pk>/edit/", views.fund_form, name="fund-edit"),
    path("expense-reports/", views.expense_list, name="expense-list"),
    path("expense-reports/create/", views.expense_form, name="expense-create"),
    path("expense-reports/<int:pk>/edit/", views.expense_form, name="expense-edit"),
    path("progress/", views.progress_list, name="progress-list"),
    path("progress/create/", views.progress_form, name="progress-create"),
    path("progress/<int:pk>/edit/", views.progress_form, name="progress-edit"),
    path("daily-reports/", views.daily_list, name="daily-list"),
    path("daily-reports/create/", views.daily_form, name="daily-create"),
    path("daily-reports/<int:pk>/edit/", views.daily_form, name="daily-edit"),
    path("attendance/", views.attendance_list, name="attendance-list"),
    path("attendance/create/", views.attendance_form, name="attendance-create"),
    path("attendance/<int:pk>/edit/", views.attendance_form, name="attendance-edit"),
    path("invoices/", views.invoice_list, name="invoice-list"),
    path("invoices/create/", views.invoice_form, name="invoice-create"),
    path("invoices/<int:pk>/edit/", views.invoice_form, name="invoice-edit"),
    path("documents/<str:document_type>/<int:pk>/delete/", views.document_delete, name="document-delete"),
    path("documents/<str:document_type>/<int:pk>/<str:action>/", views.document_action, name="document-action"),
    path("cash-flow/", views.cash_flow, name="cash-flow"),
    path("reports/", views.reports, name="report-index"),
    path("profile/", views.profile, name="profile"),
    path("administration/", views.administration, name="administration"),
    path("audit/", views.audit, name="audit"),
]
