# Generated by Django 4.2.30 on 2026-08-06 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner_type', models.CharField(choices=[('CLIENT', 'Pelanggan'), ('VENDOR', 'Vendor'), ('SUBCONTRACTOR', 'Subkontraktor')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('tax_no', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('contact', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'business_partners',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='CustomerPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('po_number', models.CharField(max_length=80)),
                ('po_date', models.DateField()),
                ('contract_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Diajukan'), ('REVIEWED', 'Diperiksa'), ('APPROVED', 'Disetujui'), ('REVISION', 'Perlu Revisi'), ('REJECTED', 'Ditolak'), ('DISBURSED', 'Dicairkan'), ('VERIFIED', 'Diverifikasi'), ('SETTLED', 'Diselesaikan'), ('CLOSED', 'Ditutup'), ('SENT', 'Dikirim'), ('PARTIALLY_PAID', 'Dibayar Sebagian'), ('PAID', 'Lunas'), ('OVERDUE', 'Jatuh Tempo'), ('CANCELLED', 'Dibatalkan')], default='DRAFT', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_customer_pos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'erp_customer_purchase_orders',
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_number', models.CharField(max_length=80)),
                ('report_date', models.DateField()),
                ('weather', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Diajukan'), ('REVIEWED', 'Diperiksa'), ('APPROVED', 'Disetujui'), ('REVISION', 'Perlu Revisi'), ('REJECTED', 'Ditolak'), ('DISBURSED', 'Dicairkan'), ('VERIFIED', 'Diverifikasi'), ('SETTLED', 'Diselesaikan'), ('CLOSED', 'Ditutup'), ('SENT', 'Dikirim'), ('PARTIALLY_PAID', 'Dibayar Sebagian'), ('PAID', 'Lunas'), ('OVERDUE', 'Jatuh Tempo'), ('CANCELLED', 'Dibatalkan')], default='DRAFT', max_length=20)),
                ('revision', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'erp_daily_reports',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_no', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='erp.company')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='FundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_number', models.CharField(max_length=80)),
                ('request_date', models.DateField()),
                ('total_requested', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('purpose', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Diajukan'), ('REVIEWED', 'Diperiksa'), ('APPROVED', 'Disetujui'), ('REVISION', 'Perlu Revisi'), ('REJECTED', 'Ditolak'), ('DISBURSED', 'Dicairkan'), ('VERIFIED', 'Diverifikasi'), ('SETTLED', 'Diselesaikan'), ('CLOSED', 'Ditutup'), ('SENT', 'Dikirim'), ('PARTIALLY_PAID', 'Dibayar Sebagian'), ('PAID', 'Lunas'), ('OVERDUE', 'Jatuh Tempo'), ('CANCELLED', 'Dibatalkan')], default='DRAFT', max_length=20)),
                ('revision', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'erp_fund_requests',
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('source_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('UPLOADED', 'Diunggah'), ('VALIDATED', 'Tervalidasi'), ('POSTED', 'Diposting'), ('FAILED', 'Gagal')], default='UPLOADED', max_length=20)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erp_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'erp_import_batches',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=80)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Diajukan'), ('REVIEWED', 'Diperiksa'), ('APPROVED', 'Disetujui'), ('REVISION', 'Perlu Revisi'), ('REJECTED', 'Ditolak'), ('DISBURSED', 'Dicairkan'), ('VERIFIED', 'Diverifikasi'), ('SETTLED', 'Diselesaikan'), ('CLOSED', 'Ditutup'), ('SENT', 'Dikirim'), ('PARTIALLY_PAID', 'Dibayar Sebagian'), ('PAID', 'Lunas'), ('OVERDUE', 'Jatuh Tempo'), ('CANCELLED', 'Dibatalkan')], default='DRAFT', max_length=20)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erp_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'erp_sales_invoices',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='erp.businesspartner')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erp_projects', to='erp.company')),
            ],
            options={
                'db_table': 'erp_projects',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('SUPERADMIN', 'Superadmin'), ('ADMIN', 'Admin'), ('MANDOR', 'Mandor'), ('LAPANGAN', 'Karyawan Lapangan')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='UserOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_organizations', to='erp.company')),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_organization', to='erp.employee')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_organizations', to='erp.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_organizations',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_code', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('unit', models.CharField(max_length=30)),
                ('qty', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.customerpurchaseorder')),
            ],
            options={
                'db_table': 'erp_purchase_order_items',
            },
        ),
        migrations.CreateModel(
            name='ProjectSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segment_code', models.CharField(max_length=50)),
                ('segment_name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='segments', to='erp.project')),
            ],
            options={
                'db_table': 'erp_project_segments',
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_role', models.CharField(choices=[('ADMIN', 'Admin Proyek'), ('MANDOR', 'Mandor'), ('LAPANGAN', 'Karyawan Lapangan')], max_length=20)),
                ('assigned_at', models.DateField()),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_memberships', to='erp.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='erp.project')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='erp.projectsegment')),
            ],
            options={
                'db_table': 'erp_project_members',
            },
        ),
        migrations.CreateModel(
            name='ProjectBudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_code', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('cost_category', models.CharField(choices=[('SERVICE', 'Jasa'), ('MATERIAL', 'Material'), ('OVERHEAD', 'Overhead'), ('PETTY_CASH', 'Petty Cash'), ('OTHER', 'Lain-lain')], max_length=20)),
                ('unit', models.CharField(max_length=30)),
                ('planned_qty', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=18)),
                ('planned_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Diajukan'), ('REVIEWED', 'Diperiksa'), ('APPROVED', 'Disetujui'), ('REVISION', 'Perlu Revisi'), ('REJECTED', 'Ditolak'), ('DISBURSED', 'Dicairkan'), ('VERIFIED', 'Diverifikasi'), ('SETTLED', 'Diselesaikan'), ('CLOSED', 'Ditutup'), ('SENT', 'Dikirim'), ('PARTIALLY_PAID', 'Dibayar Sebagian'), ('PAID', 'Lunas'), ('OVERDUE', 'Jatuh Tempo'), ('CANCELLED', 'Dibatalkan')], default='DRAFT', max_length=20)),
                ('po_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='erp.purchaseorderitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='erp.project')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='erp.projectsegment')),
            ],
            options={
                'db_table': 'erp_project_budget_lines',
            },
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_number', models.CharField(max_length=80)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Diajukan'), ('REVIEWED', 'Diperiksa'), ('APPROVED', 'Disetujui'), ('REVISION', 'Perlu Revisi'), ('REJECTED', 'Ditolak'), ('DISBURSED', 'Dicairkan'), ('VERIFIED', 'Diverifikasi'), ('SETTLED', 'Diselesaikan'), ('CLOSED', 'Ditutup'), ('SENT', 'Dikirim'), ('PARTIALLY_PAID', 'Dibayar Sebagian'), ('PAID', 'Lunas'), ('OVERDUE', 'Jatuh Tempo'), ('CANCELLED', 'Dibatalkan')], default='DRAFT', max_length=20)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_reports', to='erp.project')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_reports', to='erp.projectsegment')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erp_progress_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'erp_progress_reports',
            },
        ),
        migrations.CreateModel(
            name='ProgressItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_qty', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('current_qty', models.DecimalField(decimal_places=4, max_digits=18)),
                ('approved_qty', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('budget_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_items', to='erp.projectbudgetline')),
                ('progress_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.progressreport')),
            ],
            options={
                'db_table': 'erp_progress_items',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('method', models.CharField(blank=True, max_length=30)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erp_payments', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='erp.invoice')),
            ],
            options={
                'db_table': 'erp_payments',
            },
        ),
        migrations.CreateModel(
            name='MaterialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material_name', models.CharField(max_length=255)),
                ('qty', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit', models.CharField(max_length=30)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_usages', to='erp.dailyreport')),
            ],
            options={
                'db_table': 'erp_material_usages',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('qty', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('item_type', models.CharField(default='PROGRESS', max_length=30)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.invoice')),
                ('progress_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='erp.progressitem')),
            ],
            options={
                'db_table': 'erp_invoice_items',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='erp.project'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='erp.customerpurchaseorder'),
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sheet_name', models.CharField(max_length=255)),
                ('row_number', models.PositiveIntegerField()),
                ('business_key', models.CharField(blank=True, max_length=255)),
                ('fingerprint', models.CharField(max_length=64)),
                ('raw_payload', models.JSONField(default=dict)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu'), ('VALID', 'Valid'), ('DUPLICATE', 'Duplikat'), ('CONFLICT', 'Konflik'), ('INVALID', 'Tidak Valid'), ('POSTED', 'Diposting')], default='PENDING', max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='erp.importbatch')),
            ],
            options={
                'db_table': 'erp_import_rows',
            },
        ),
        migrations.CreateModel(
            name='FundRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('qty', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('budget_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fund_request_items', to='erp.projectbudgetline')),
                ('fund_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.fundrequest')),
            ],
            options={
                'db_table': 'erp_fund_request_items',
            },
        ),
        migrations.AddField(
            model_name='fundrequest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fund_requests', to='erp.project'),
        ),
        migrations.AddField(
            model_name='fundrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erp_fund_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ExpenseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_number', models.CharField(max_length=80)),
                ('report_date', models.DateField()),
                ('total_actual', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Diajukan'), ('REVIEWED', 'Diperiksa'), ('APPROVED', 'Disetujui'), ('REVISION', 'Perlu Revisi'), ('REJECTED', 'Ditolak'), ('DISBURSED', 'Dicairkan'), ('VERIFIED', 'Diverifikasi'), ('SETTLED', 'Diselesaikan'), ('CLOSED', 'Ditutup'), ('SENT', 'Dikirim'), ('PARTIALLY_PAID', 'Dibayar Sebagian'), ('PAID', 'Lunas'), ('OVERDUE', 'Jatuh Tempo'), ('CANCELLED', 'Dibatalkan')], default='DRAFT', max_length=20)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('fund_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_reports', to='erp.fundrequest')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_reports', to='erp.project')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erp_expense_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'erp_expense_reports',
            },
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_date', models.DateField()),
                ('category', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('budget_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_items', to='erp.projectbudgetline')),
                ('expense_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.expensereport')),
            ],
            options={
                'db_table': 'erp_expense_items',
            },
        ),
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disbursement_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('method', models.CharField(max_length=30)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erp_disbursements', to=settings.AUTH_USER_MODEL)),
                ('fund_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursements', to='erp.fundrequest')),
            ],
            options={
                'db_table': 'erp_disbursements',
            },
        ),
        migrations.CreateModel(
            name='DailyReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_description', models.TextField()),
                ('qty_done', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit', models.CharField(max_length=30)),
                ('budget_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_report_items', to='erp.projectbudgetline')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.dailyreport')),
            ],
            options={
                'db_table': 'erp_daily_report_items',
            },
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_reports', to='erp.project'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_reports', to='erp.projectsegment'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erp_daily_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerpurchaseorder',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='erp.project'),
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_date', models.DateField()),
                ('direction', models.CharField(choices=[('IN', 'Masuk'), ('OUT', 'Keluar')], max_length=3)),
                ('category', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('source_type', models.CharField(max_length=40)),
                ('source_id', models.PositiveBigIntegerField()),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_transactions', to='erp.project')),
            ],
            options={
                'db_table': 'erp_cash_transactions',
            },
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_partners', to='erp.company'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_date', models.DateField()),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='erp.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='erp.project')),
            ],
            options={
                'db_table': 'erp_attendances',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(max_length=40)),
                ('document_id', models.PositiveBigIntegerField()),
                ('file', models.FileField(upload_to='erp/attachments/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erp_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'erp_attachments',
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(max_length=40)),
                ('document_id', models.PositiveBigIntegerField()),
                ('step_no', models.PositiveSmallIntegerField(default=1)),
                ('decision', models.CharField(choices=[('PENDING', 'Menunggu'), ('APPROVED', 'Disetujui'), ('REVISION', 'Revisi'), ('REJECTED', 'Ditolak')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erp_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'erp_approvals',
            },
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'item_code'), name='uq_po_item_code'),
        ),
        migrations.AddConstraint(
            model_name='projectsegment',
            constraint=models.UniqueConstraint(fields=('project', 'segment_code'), name='uq_erp_project_segment'),
        ),
        migrations.AddConstraint(
            model_name='projectmember',
            constraint=models.UniqueConstraint(fields=('project', 'segment', 'employee', 'assigned_at'), name='uq_project_member_period'),
        ),
        migrations.AddIndex(
            model_name='projectbudgetline',
            index=models.Index(fields=['project', 'segment', 'cost_category'], name='erp_project_project_3a98a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectbudgetline',
            constraint=models.UniqueConstraint(fields=('project', 'segment', 'line_code', 'version'), name='uq_budget_line_version'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['company', 'status'], name='erp_project_company_5814d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('company', 'project_code'), name='uq_project_company_code'),
        ),
        migrations.AddIndex(
            model_name='progressreport',
            index=models.Index(fields=['project', 'segment', 'period_start', 'status'], name='erp_progres_project_fe80a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='progressreport',
            constraint=models.UniqueConstraint(fields=('project', 'report_number'), name='uq_progress_report_number'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['project', 'status', 'invoice_date'], name='erp_sales_i_project_e220ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('project', 'invoice_number', 'revision'), name='uq_invoice_revision'),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['business_key', 'fingerprint'], name='erp_import__busines_142d84_idx'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.UniqueConstraint(fields=('batch', 'sheet_name', 'row_number'), name='uq_import_source_row'),
        ),
        migrations.AddIndex(
            model_name='fundrequest',
            index=models.Index(fields=['project', 'status', 'request_date'], name='erp_fund_re_project_ab0fa9_idx'),
        ),
        migrations.AddConstraint(
            model_name='fundrequest',
            constraint=models.UniqueConstraint(fields=('project', 'request_number'), name='uq_fund_request_number'),
        ),
        migrations.AddIndex(
            model_name='expensereport',
            index=models.Index(fields=['project', 'status', 'report_date'], name='erp_expense_project_3938f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='expensereport',
            constraint=models.UniqueConstraint(fields=('project', 'report_number'), name='uq_expense_report_number'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('company', 'employee_no'), name='uq_employee_company_no'),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['project', 'segment', 'report_date', 'status'], name='erp_daily_r_project_f58d69_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyreport',
            constraint=models.UniqueConstraint(fields=('project', 'report_number'), name='uq_daily_report_number'),
        ),
        migrations.AddIndex(
            model_name='customerpurchaseorder',
            index=models.Index(fields=['project', 'status', 'po_date'], name='erp_custome_project_a0e2c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerpurchaseorder',
            constraint=models.UniqueConstraint(fields=('project', 'po_number'), name='uq_project_po_number'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['project', 'transaction_date'], name='erp_cash_tr_project_c11dae_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['source_type', 'source_id'], name='erp_cash_tr_source__2d6425_idx'),
        ),
        migrations.AddIndex(
            model_name='businesspartner',
            index=models.Index(fields=['company', 'partner_type', 'name'], name='business_pa_company_41d3c1_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['project', 'work_date', 'employee'], name='erp_attenda_project_bd8941_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('project', 'employee', 'work_date'), name='uq_attendance_day'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['document_type', 'document_id'], name='erp_attachm_documen_c60980_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['document_type', 'document_id', 'step_no'], name='erp_approva_documen_3813c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='approval',
            constraint=models.UniqueConstraint(fields=('document_type', 'document_id', 'step_no'), name='uq_document_approval_step'),
        ),
    ]
