# Generated by Django 4.2.30 on 2026-08-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbudgetline',
            name='expense_purpose',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectbudgetline',
            name='foreman_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
