# Generated by Django 4.2.30 on 2026-08-19 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0002_projectbudgetline_expense_purpose_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeOverhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_date', models.DateField()),
                ('category', models.CharField(choices=[('ELECTRICITY', 'Listrik'), ('SALARY', 'Gaji Karyawan'), ('MEALS', 'Uang Makan'), ('PETTY_CASH', 'Petty Cash'), ('INTERNET', 'Internet & Telepon'), ('RENT', 'Sewa Kantor'), ('TRANSPORT', 'Transportasi'), ('SUPPLIES', 'ATK & Perlengkapan'), ('OTHER', 'Lain-lain')], max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, upload_to='erp/attachments/overhead/%Y/%m/')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_office_overheads', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='office_overheads', to='erp.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='office_overheads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'erp_office_overheads',
                'ordering': ['-expense_date', '-id'],
                'indexes': [models.Index(fields=['company', 'expense_date', 'category'], name='erp_office__company_4d1a84_idx')],
            },
        ),
    ]
