# Generated by Django 4.2.30 on 2026-08-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_officeoverhead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officeoverhead',
            name='reference_number',
        ),
        migrations.AddField(
            model_name='projectbudgetline',
            name='span',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='projectbudgetline',
            name='worker_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='officeoverhead',
            name='attachment',
            field=models.ImageField(blank=True, upload_to='erp/attachments/overhead/%Y/%m/', verbose_name='Foto Bukti'),
        ),
    ]
