# Generated by Django 4.2.30 on 2026-08-21 14:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0004_remove_officeoverhead_reference_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(max_length=30)),
                ('warehouse_qty', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('field_qty', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('image', models.ImageField(blank=True, upload_to='erp/materials/%Y/%m/')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_materials', to='erp.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_warehouse_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'erp_warehouse_materials',
                'ordering': ['name', 'unit'],
            },
        ),
        migrations.CreateModel(
            name='MaterialMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('TAKE', 'Diambil ke Lapangan'), ('RETURN', 'Dikembalikan ke Gudang')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('movement_date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True)),
                ('foreman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_movements', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='erp.warehousematerial')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_movements', to='erp.project')),
            ],
            options={
                'db_table': 'erp_material_movements',
                'ordering': ['-movement_date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='warehousematerial',
            constraint=models.UniqueConstraint(fields=('company', 'name', 'unit'), name='uq_warehouse_material_company_name_unit'),
        ),
        migrations.AddIndex(
            model_name='materialmovement',
            index=models.Index(fields=['project', 'movement_type', 'movement_date'], name='erp_materia_project_5f7da2_idx'),
        ),
    ]
