from django.urls import include,path,re_path
from django.views.generic import RedirectView
from portal import views as v
from django.conf import settings
from django.conf.urls.static import static
urlpatterns=[path('',RedirectView.as_view(pattern_name='erp:dashboard',permanent=False)),path('login',lambda r:v.page(r,'erp/auth/login.html')),path('dashboard',RedirectView.as_view(pattern_name='erp:dashboard',permanent=False)),path('dashboard/project/<int:project_id>',RedirectView.as_view(pattern_name='erp:project-dashboard',permanent=False)),path('erp/',include('erp.urls')),
path('api/',v.health),path('api/health',v.health),path('api/auth/<str:action>',v.auth_api),
re_path(r'^api/supervisi/laporan/?$',v.supervisi_api),path('api/supervisi/laporan/foto/<int:id>',lambda r,id:v.supervisi_api(r,id,'delete-foto')),path('api/supervisi/laporan/<int:id>/foto',lambda r,id:v.supervisi_api(r,id,'foto')),path('api/supervisi/laporan/<int:id>',v.supervisi_api),re_path(r'^api/supervisi/evidence/?$',v.supervisi_evidence),
re_path(r'^api/customers/?$',v.customers),path('api/customers/<int:id>',v.customers),
re_path(r'^api/projects/?$',v.projects),path('api/projects/rab/<int:item>',lambda r,item:v.project_nested_legacy(r,'rab',item)),path('api/projects/timeline/<int:item>',lambda r,item:v.project_nested_legacy(r,'timeline',item)),path('api/projects/<int:id>',v.projects),path('api/projects/<int:id>/<str:sub>',v.projects),path('api/projects/<int:id>/<str:sub>/<str:item>',v.projects),
re_path(r'^api/invoices/?$',v.invoices),path('api/invoices/summary',lambda r:v.invoices(r,action='summary')),path('api/invoices/<int:id>',v.invoices),path('api/invoices/<int:id>/<str:action>',v.invoices),
re_path(r'^api/materials/?$',v.material_api),path('api/materials/budget',lambda r:v.material_api(r,action='budget')),path('api/materials/<int:id>',v.material_api),path('api/materials/<int:id>/move',lambda r,id:v.material_api(r,id,'move')),
re_path(r'^api/petty-cash/?$',v.petty_api),path('api/petty-cash/summary/by-category',lambda r:v.petty_api(r,action='summary')),path('api/petty-cash/budget',lambda r:v.petty_api(r,action='budget')),path('api/petty-cash/<int:id>',v.petty_api),
re_path(r'^api/overhead/?$',v.overhead_api),path('api/overhead/kategori',lambda r:v.overhead_api(r,action='kategori')),path('api/overhead/summary',lambda r:v.overhead_api(r,action='summary')),path('api/overhead/<int:id>',v.overhead_api),
re_path(r'^api/absen/?$',v.absen_api),path('api/absen/foto/<int:id>',lambda r,id:v.absen_api(r,id,'delete-foto')),path('api/absen/<int:id>/foto',lambda r,id:v.absen_api(r,id,'foto')),path('api/absen/<int:id>',v.absen_api),
re_path(r'^api/kasbon/?$',v.kasbon_api),path('api/kasbon/summary',lambda r:v.kasbon_api(r,action='summary')),path('api/kasbon/<int:id>/<str:action>',v.kasbon_api),path('api/kasbon/<int:id>',v.kasbon_api),
re_path(r'^api/log/?$',v.log_api),path('api/log/<str:action>',v.log_api),
path('api/projects/<int:project_id>/overhead/summary',lambda r,project_id:v.project_overhead(r,project_id,kind='summary')),path('api/projects/<int:project_id>/overhead/kasbon-mandor',lambda r,project_id:v.project_overhead(r,project_id,kind='kasbon')),path('api/projects/<int:project_id>/overhead/kasbon-mandor/<int:id>',lambda r,project_id,id:v.project_overhead(r,project_id,id,'kasbon')),path('api/projects/<int:project_id>/overhead',v.project_overhead),path('api/projects/<int:project_id>/overhead/<int:id>',v.project_overhead),
re_path(r'^api/settings/?$',v.settings_api),path('api/settings/<str:sub>',v.settings_api),path('api/settings/<str:sub>/<int:id>',v.settings_api),path('api/settings/profile/avatar',lambda r:v.upload(r,'avatar',r.user.id)),
]
redirects={'project-po':'erp:project-list','project-non-po':'erp:project-list','invoice':'erp:invoice-list','absen':'erp:attendance-list','arsip':'erp:project-list','arsip/invoice':'erp:invoice-list','arsip/project':'erp:project-list','material':'erp:project-list','petty-cash':'erp:expense-list','overhead':'erp:expense-list','verifikasi-kasbon':'erp:fund-list','mandor/request-kasbon':'erp:fund-list','mandor/request-kasbon.html':'erp:fund-list','pengajuan-kasbon':'erp:fund-list','supervisi/absen':'erp:attendance-list','supervisi/absen.html':'erp:attendance-list','supervisi/absen-supervisi.html':'erp:attendance-list','supervisi/evidence-foto':'erp:daily-list','supervisi/evidence-foto.html':'erp:daily-list','supervisi/laporan-kegiatan':'erp:daily-list','supervisi/laporan-kegiatan.html':'erp:daily-list','log-aktivitas':'erp:audit','profile':'erp:profile','setting':'erp:administration','mandor/profile':'erp:profile','mandor/profile.html':'erp:profile','supervisi/profile':'erp:profile','supervisi/profile-supervisi.html':'erp:profile'}
for u,name in redirects.items():urlpatterns.append(path(u,RedirectView.as_view(pattern_name=name,permanent=False)))
legacy_redirects={'project/<int:project_id>/jasa':'erp:project-services','project/<int:project_id>/overhead':'erp:project-overhead'}
for u,name in legacy_redirects.items():urlpatterns.append(path(u,RedirectView.as_view(pattern_name=name,permanent=False)))
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
