from django.urls import path,re_path
from portal import views as v
from portal import erp
from django.conf import settings
from django.conf.urls.static import static
urlpatterns=[path('',v.index),path('login',lambda r:v.page(r,'login.html')),path('dashboard',v.dashboard),path('dashboard/project/<int:project_id>',v.dashboard),path('erp/',erp.dashboard,name='erp-dashboard'),path('erp/create/<str:kind>/',erp.create,name='erp-create'),path('erp/decision/<str:module>/<int:pk>/<str:decision>/',erp.decide,name='erp-decide'),
path('api/',v.health),path('api/health',v.health),path('api/auth/<str:action>',v.auth_api),
re_path(r'^api/supervisi/laporan/?$',v.supervisi_api),path('api/supervisi/laporan/foto/<int:id>',lambda r,id:v.supervisi_api(r,id,'delete-foto')),path('api/supervisi/laporan/<int:id>/foto',lambda r,id:v.supervisi_api(r,id,'foto')),path('api/supervisi/laporan/<int:id>',v.supervisi_api),re_path(r'^api/supervisi/evidence/?$',v.supervisi_evidence),
re_path(r'^api/customers/?$',v.customers),path('api/customers/<int:id>',v.customers),
re_path(r'^api/projects/?$',v.projects),path('api/projects/rab/<int:item>',lambda r,item:v.project_nested_legacy(r,'rab',item)),path('api/projects/timeline/<int:item>',lambda r,item:v.project_nested_legacy(r,'timeline',item)),path('api/projects/<int:id>',v.projects),path('api/projects/<int:id>/<str:sub>',v.projects),path('api/projects/<int:id>/<str:sub>/<str:item>',v.projects),
re_path(r'^api/invoices/?$',v.invoices),path('api/invoices/summary',lambda r:v.invoices(r,action='summary')),path('api/invoices/<int:id>',v.invoices),path('api/invoices/<int:id>/<str:action>',v.invoices),
re_path(r'^api/materials/?$',v.material_api),path('api/materials/budget',lambda r:v.material_api(r,action='budget')),path('api/materials/<int:id>',v.material_api),path('api/materials/<int:id>/move',lambda r,id:v.material_api(r,id,'move')),
re_path(r'^api/petty-cash/?$',v.petty_api),path('api/petty-cash/summary/by-category',lambda r:v.petty_api(r,action='summary')),path('api/petty-cash/budget',lambda r:v.petty_api(r,action='budget')),path('api/petty-cash/<int:id>',v.petty_api),
re_path(r'^api/overhead/?$',v.overhead_api),path('api/overhead/kategori',lambda r:v.overhead_api(r,action='kategori')),path('api/overhead/summary',lambda r:v.overhead_api(r,action='summary')),path('api/overhead/<int:id>',v.overhead_api),
re_path(r'^api/absen/?$',v.absen_api),path('api/absen/foto/<int:id>',lambda r,id:v.absen_api(r,id,'delete-foto')),path('api/absen/<int:id>/foto',lambda r,id:v.absen_api(r,id,'foto')),path('api/absen/<int:id>',v.absen_api),
re_path(r'^api/kasbon/?$',v.kasbon_api),path('api/kasbon/summary',lambda r:v.kasbon_api(r,action='summary')),path('api/kasbon/<int:id>/<str:action>',v.kasbon_api),path('api/kasbon/<int:id>',v.kasbon_api),
re_path(r'^api/log/?$',v.log_api),path('api/log/<str:action>',v.log_api),
path('api/projects/<int:project_id>/overhead/summary',lambda r,project_id:v.project_overhead(r,project_id,kind='summary')),path('api/projects/<int:project_id>/overhead/kasbon-mandor',lambda r,project_id:v.project_overhead(r,project_id,kind='kasbon')),path('api/projects/<int:project_id>/overhead/kasbon-mandor/<int:id>',lambda r,project_id,id:v.project_overhead(r,project_id,id,'kasbon')),path('api/projects/<int:project_id>/overhead',v.project_overhead),path('api/projects/<int:project_id>/overhead/<int:id>',v.project_overhead),
re_path(r'^api/settings/?$',v.settings_api),path('api/settings/<str:sub>',v.settings_api),path('api/settings/<str:sub>/<int:id>',v.settings_api),path('api/settings/profile/avatar',lambda r:v.upload(r,'avatar',r.user.id)),
]
pages={'project-po':'project po.html','project-non-po':'project non-po.html','invoice':'invoice.html','overhead':'overhead kantor.html','absen':'absen.html','arsip':'beranda arsip.html','arsip/invoice':'arsip invoice.html','arsip/project':'arsip project.html','log-aktivitas':'log aktivitas.html','profile':'profile.html','setting':'setting.html','material':'material.html','petty-cash':'petty_cash.html','verifikasi-kasbon':'verifikasi kasbon.html','mandor/profile':'mandor/profile.html','mandor/profile.html':'mandor/profile.html','mandor/request-kasbon':'mandor/request kasbon.html','mandor/request-kasbon.html':'mandor/request kasbon.html','supervisi/profile':'supervisi/profile.html','supervisi/absen':'supervisi/absen.html','supervisi/evidence-foto':'supervisi/evidence foto.html','supervisi/laporan-kegiatan':'supervisi/laporan kegiatan.html'}
for u,t in pages.items():urlpatterns.append(path(u,lambda r,t=t:v.page(r,t)))
legacy_pages={'project/<int:project_id>/jasa':'jasa.html','project/<int:project_id>/overhead':'project_overhead.html','pengajuan-kasbon':'mandor/request kasbon.html','supervisi/profile-supervisi.html':'supervisi/profile.html','supervisi/absen.html':'supervisi/absen.html','supervisi/absen-supervisi.html':'supervisi/absen.html','supervisi/evidence-foto.html':'supervisi/evidence foto.html','supervisi/laporan-kegiatan.html':'supervisi/laporan kegiatan.html'}
for u,t in legacy_pages.items():urlpatterns.append(path(u,lambda r,project_id=None,t=t:v.page(r,t,project_id=project_id)))
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
